<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="amit" name="TestCalc" tests="4" failures="1" timestamp="6 Mar 2016 12:29:42 GMT" time="2.047" errors="0">
  <testcase name="testAddTwoStrings" time="0.001" classname="TestCalc"/>
  <testcase name="testAddTwoIntegers" time="1.016" classname="TestCalc"/>
  <testcase name="testAddTwoNegative" time="1.003" classname="TestCalc"/>
  <testcase name="testAddTwoIntegersUnder10sec" time="0.027" classname="TestCalc">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testAddTwoIntegersUnder10sec() didn&#039;t finish within the time-out 1">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testAddTwoIntegersUnder10sec() didn't finish within the time-out 1
	at java.util.IdentityHashMap.init(Unknown Source)
	at java.util.IdentityHashMap.<init>(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at Calc.add(Calc.java:8)
	at TestCalc.testAddTwoIntegersUnder10sec(TestCalc.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testAddTwoIntegersUnder10sec -->
</testsuite> <!-- TestCalc -->
