<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2073" started-at="2016-03-06T12:29:40Z" finished-at="2016-03-06T12:29:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2073" started-at="2016-03-06T12:29:40Z" finished-at="2016-03-06T12:29:42Z">
      <class name="TestCalc">
        <test-method status="PASS" signature="testAddTwoIntegers()[pri:0, instance:TestCalc@1c2c22f3]" name="testAddTwoIntegers" duration-ms="1016" started-at="2016-03-06T17:59:40Z" finished-at="2016-03-06T17:59:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddTwoIntegers -->
        <test-method status="FAIL" signature="testAddTwoIntegersUnder10sec()[pri:0, instance:TestCalc@1c2c22f3]" name="testAddTwoIntegersUnder10sec" duration-ms="27" started-at="2016-03-06T17:59:41Z" finished-at="2016-03-06T17:59:41Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method org.testng.internal.TestNGMethod.testAddTwoIntegersUnder10sec() didn't finish within the time-out 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testAddTwoIntegersUnder10sec() didn't finish within the time-out 1
	at java.util.IdentityHashMap.init(Unknown Source)
	at java.util.IdentityHashMap.<init>(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at Calc.add(Calc.java:8)
	at TestCalc.testAddTwoIntegersUnder10sec(TestCalc.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddTwoIntegersUnder10sec -->
        <test-method status="PASS" signature="testAddTwoNegative()[pri:0, instance:TestCalc@1c2c22f3]" name="testAddTwoNegative" duration-ms="1003" started-at="2016-03-06T17:59:41Z" finished-at="2016-03-06T17:59:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddTwoNegative -->
        <test-method status="PASS" signature="testAddTwoStrings()[pri:0, instance:TestCalc@1c2c22f3]" name="testAddTwoStrings" duration-ms="1" started-at="2016-03-06T17:59:42Z" finished-at="2016-03-06T17:59:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddTwoStrings -->
      </class> <!-- TestCalc -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
